import type { MapInfo } from "@/db/schema";

export const OverwatchMaps: MapInfo[] = [
    {
        id: 1,
        name: "Antarctic Peninsula",
        image: "/mapImages/overwatch/antarctic.png",
        mode: "Control",
        winner: null,
    },
    {
        id: 2,
        name: "Blizzard World",
        image: "/mapImages/overwatch/blizzardWorld.jpg",
        mode: "Hybrid",
        winner: null,
    },
    {
        id: 3,
        name: "Busan",
        image: "/mapImages/overwatch/busan.jpg",
        mode: "Control",
        winner: null,
    },
    {
        id: 4,
        name: "Circuit Royale",
        image: "/mapImages/overwatch/circuit.jpg",
        mode: "Escort",
        winner: null,
    },
    {
        id: 5,
        name: "Colosseo",
        image: "/mapImages/overwatch/collosseo.png",
        mode: "Push",
        winner: null,
    },
    {
        id: 6,
        name: "Dorado",
        image: "/mapImages/overwatch/dorado.jpg",
        mode: "Escort",
        winner: null,
    },
    {
        id: 7,
        name: "Eichenwalde",
        image: "/mapImages/overwatch/eichenwalde.png",
        mode: "Hybrid",
        winner: null,
    },
    {
        id: 8,
        name: "Esperança",
        image: "/mapImages/overwatch/esperanca.jpg",
        mode: "Push",
        winner: null,
    },
    {
        id: 9,
        name: "Gibraltar",
        image: "/mapImages/overwatch/gibraltar.jpg",
        mode: "Escort",
        winner: null,
    },
    {
        id: 10,
        name: "Hanaoka",
        image: "/mapImages/overwatch/hanaoka.jpg",
        mode: "Clash",
        winner: null,
    },
    {
        id: 11,
        name: "Havana",
        image: "/mapImages/overwatch/havana.png",
        mode: "Escort",
        winner: null,
    },
    {
        id: 12,
        name: "Hollywood",
        image: "/mapImages/overwatch/hollywood.jpg",
        mode: "Hybrid",
        winner: null,
    },
    {
        id: 13,
        name: "Ilios",
        image: "/mapImages/overwatch/ilios.jpg",
        mode: "Control",
        winner: null,
    },
    {
        id: 14,
        name: "Junkertown",
        image: "/mapImages/overwatch/junkertown.jpg",
        mode: "Escort",
        winner: null,
    },
    {
        id: 15,
        name: "King's Row",
        image: "/mapImages/overwatch/kingsRow.jpg",
        mode: "Hybrid",
        winner: null,
    },
    {
        id: 16,
        name: "Lijiang Tower",
        image: "/mapImages/overwatch/lijiangTower.jpg",
        mode: "Control",
        winner: null,
    },
    {
        id: 17,
        name: "Midtown",
        image: "/mapImages/overwatch/midtown.png",
        mode: "Hybrid",
        winner: null,
    },
    {
        id: 18,
        name: "Nepal",
        image: "/mapImages/overwatch/nepal.jpg",
        mode: "Control",
        winner: null,
    },
    {
        id: 19,
        name: "New Junk City",
        image: "/mapImages/overwatch/newJunkCity.jpg",
        mode: "Flashpoint",
        winner: null,
    },
    {
        id: 20,
        name: "New Queen Street",
        image: "/mapImages/overwatch/newQueensStreet.jpg",
        mode: "Push",
        winner: null,
    },
    {
        id: 21,
        name: "Numbani",
        image: "/mapImages/overwatch/numbani.jpg",
        mode: "Hybrid",
        winner: null,
    },
    {
        id: 22,
        name: "Oasis",
        image: "/mapImages/overwatch/oasis.jpg",
        mode: "Control",
        winner: null,
    },
    {
        id: 23,
        name: "Paraiso",
        image: "/mapImages/overwatch/paraiso.jpg",
        mode: "Hybrid",
        winner: null,
    },
    {
        id: 24,
        name: "Rialto",
        image: "/mapImages/overwatch/rialto.jpg",
        mode: "Escort",
        winner: null,
    },
    {
        id: 25,
        name: "Route 66",
        image: "/mapImages/overwatch/route66.jpg",
        mode: "Escort",
        winner: null,
    },
    {
        id: 26,
        name: "Runasapi",
        image: "/mapImages/overwatch/runasapi.jpg",
        mode: "Control",
        winner: null,
    },
    {
        id: 27,
        name: "Samoa",
        image: "/mapImages/overwatch/samoa.jpg",
        mode: "Control",
        winner: null,
    },
    {
        id: 28,
        name: "Shambali Monastery",
        image: "/mapImages/overwatch/shambali.png",
        mode: "Escort",
        winner: null,
    },
    {
        id: 29,
        name: "Suravasa",
        image: "/mapImages/overwatch/suravasa.jpg",
        mode: "Push",
        winner: null,
    },
    {
        id: 30,
        name: "Throne of Anubis",
        image: "/mapImages/overwatch/throneOfAnubsi.png",
        mode: "Clash",
        winner: null,
    },
];

export const SplatoonMaps: MapInfo[] = [];

export const ValorantMaps: MapInfo[] = [
    {
        id: 1,
        name: "Bind",
        image: `/mapImages/valorant/bind.jpg`,
        mode: null,
        winner: null,
    },
    {
        id: 2,
        name: "Haven",
        image: `/mapImages/valorant/haven.jpg`,
        mode: null,
        winner: null,
    },
    {
        id: 3,
        name: "Split",
        image: `/mapImages/valorant/split.jpg`,
        mode: null,
        winner: null,
    },
    {
        id: 4,
        name: "Ascent",
        image: `/mapImages/valorant/ascent.jpg`,
        mode: null,
        winner: null,
    },
    {
        id: 5,
        name: "Icebox",
        image: `/mapImages/valorant/icebox.jpg`,
        mode: null,
        winner: null,
    },
    {
        id: 6,
        name: "Breeze",
        image: `/mapImages/valorant/breeze.jpg`,
        mode: null,
        winner: null,
    },
    {
        id: 7,
        name: "Fracture",
        image: `/mapImages/valorant/fracture.jpg`,
        mode: null,
        winner: null,
    },
    {
        id: 8,
        name: "Pearl",
        image: `/mapImages/valorant/pearl.jpg`,
        mode: null,
        winner: null,
    },
    {
        id: 9,
        name: "Lotus",
        image: `/mapImages/valorant/lotus.jpeg`,
        mode: null,
        winner: null,
    },
    {
        id: 10,
        name: "Sunset",
        image: `/mapImages/valorant/sunset.png`,
        mode: null,
        winner: null,
    },
    {
        id: 11,
        name: "Abyss",
        image: "/mapImages/valorant/abyss.avif",
        mode: null,
        winner: null,
    },
];

export const CSMaps: MapInfo[] = [
    {
        id: 1,
        name: "Ancient",
        image: "/mapImages/cs/ancient.jpg",
        mode: null,
        winner: null,
    },
    {
        id: 2,
        name: "Anubis",
        image: "/mapImages/cs/anubis.jpg",
        mode: null,
        winner: null,
    },
    {
        id: 3,
        name: "Dust II",
        image: "/mapImages/cs/dust2.jpg",
        mode: null,
        winner: null,
    },
    {
        id: 4,
        name: "Inferno",
        image: "/mapImages/cs/inferno.jpeg",
        mode: null,
        winner: null,
    },
    {
        id: 5,
        name: "Mills",
        image: "/mapImages/cs/mills.png",
        mode: null,
        winner: null,
    },
    {
        id: 6,
        name: "Mirage",
        image: "/mapImages/cs/mirage.jpg",
        mode: null,
        winner: null,
    },
    {
        id: 7,
        name: "Nuke",
        image: "/mapImages/cs/nuke.jpeg",
        mode: null,
        winner: null,
    },
    {
        id: 8,
        name: "Overpass",
        image: "/mapImages/cs/overpass.jpg",
        mode: null,
        winner: null,
    },
    {
        id: 9,
        name: "Thera",
        image: "/mapImages/cs/thera.jpg",
        mode: null,
        winner: null,
    },
    {
        id: 10,
        name: "Vertigo",
        image: "/mapImages/cs/vertigo.jpeg",
        mode: null,
        winner: null,
    },
];

export const DefaultMaps: MapInfo[] = [
    {
        id: 1,
        name: "No Actual Maps",
        image: "",
        mode: null,
        winner: null,
    },
]