version: "3.8"

services:
    # Migration service - runs once and exits
    migrate:
        build: .
        container_name: stream-manager-migrate
        environment:
            NODE_ENV: production
            DATABASE_URL: postgresql://stream_manager:${POSTGRES_PASSWORD:-stream_manager_password}@postgres:5432/stream_manager
            SKIP_ENV_VALIDATION: 1
        depends_on:
            postgres:
                condition: service_healthy
        command: ["bun", "scripts/migrate.js"]
        profiles:
            - migrate
