/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewImport } from './routes/new'
import { Route as IndexImport } from './routes/index'
import { Route as SessionSessionIdImport } from './routes/session.$sessionId'
import { Route as OverlaysSessionIdWaitingForNextImport } from './routes/overlays/$sessionId/waitingForNext'
import { Route as OverlaysSessionIdThanksImport } from './routes/overlays/$sessionId/thanks'
import { Route as OverlaysSessionIdStartingSoonImport } from './routes/overlays/$sessionId/startingSoon'
import { Route as OverlaysSessionIdMatchImport } from './routes/overlays/$sessionId/match'
import { Route as OverlaysSessionIdMapsImport } from './routes/overlays/$sessionId/maps'
import { Route as OverlaysSessionIdBrbImport } from './routes/overlays/$sessionId/brb'
import { Route as OverlaysSessionIdVictoryWinnerImport } from './routes/overlays/$sessionId/victory.$winner'

// Create/Update Routes

const NewRoute = NewImport.update({
  path: '/new',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SessionSessionIdRoute = SessionSessionIdImport.update({
  path: '/session/$sessionId',
  getParentRoute: () => rootRoute,
} as any)

const OverlaysSessionIdWaitingForNextRoute =
  OverlaysSessionIdWaitingForNextImport.update({
    path: '/overlays/$sessionId/waitingForNext',
    getParentRoute: () => rootRoute,
  } as any)

const OverlaysSessionIdThanksRoute = OverlaysSessionIdThanksImport.update({
  path: '/overlays/$sessionId/thanks',
  getParentRoute: () => rootRoute,
} as any)

const OverlaysSessionIdStartingSoonRoute =
  OverlaysSessionIdStartingSoonImport.update({
    path: '/overlays/$sessionId/startingSoon',
    getParentRoute: () => rootRoute,
  } as any)

const OverlaysSessionIdMatchRoute = OverlaysSessionIdMatchImport.update({
  path: '/overlays/$sessionId/match',
  getParentRoute: () => rootRoute,
} as any)

const OverlaysSessionIdMapsRoute = OverlaysSessionIdMapsImport.update({
  path: '/overlays/$sessionId/maps',
  getParentRoute: () => rootRoute,
} as any)

const OverlaysSessionIdBrbRoute = OverlaysSessionIdBrbImport.update({
  path: '/overlays/$sessionId/brb',
  getParentRoute: () => rootRoute,
} as any)

const OverlaysSessionIdVictoryWinnerRoute =
  OverlaysSessionIdVictoryWinnerImport.update({
    path: '/overlays/$sessionId/victory/$winner',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewImport
      parentRoute: typeof rootRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdImport
      parentRoute: typeof rootRoute
    }
    '/overlays/$sessionId/brb': {
      id: '/overlays/$sessionId/brb'
      path: '/overlays/$sessionId/brb'
      fullPath: '/overlays/$sessionId/brb'
      preLoaderRoute: typeof OverlaysSessionIdBrbImport
      parentRoute: typeof rootRoute
    }
    '/overlays/$sessionId/maps': {
      id: '/overlays/$sessionId/maps'
      path: '/overlays/$sessionId/maps'
      fullPath: '/overlays/$sessionId/maps'
      preLoaderRoute: typeof OverlaysSessionIdMapsImport
      parentRoute: typeof rootRoute
    }
    '/overlays/$sessionId/match': {
      id: '/overlays/$sessionId/match'
      path: '/overlays/$sessionId/match'
      fullPath: '/overlays/$sessionId/match'
      preLoaderRoute: typeof OverlaysSessionIdMatchImport
      parentRoute: typeof rootRoute
    }
    '/overlays/$sessionId/startingSoon': {
      id: '/overlays/$sessionId/startingSoon'
      path: '/overlays/$sessionId/startingSoon'
      fullPath: '/overlays/$sessionId/startingSoon'
      preLoaderRoute: typeof OverlaysSessionIdStartingSoonImport
      parentRoute: typeof rootRoute
    }
    '/overlays/$sessionId/thanks': {
      id: '/overlays/$sessionId/thanks'
      path: '/overlays/$sessionId/thanks'
      fullPath: '/overlays/$sessionId/thanks'
      preLoaderRoute: typeof OverlaysSessionIdThanksImport
      parentRoute: typeof rootRoute
    }
    '/overlays/$sessionId/waitingForNext': {
      id: '/overlays/$sessionId/waitingForNext'
      path: '/overlays/$sessionId/waitingForNext'
      fullPath: '/overlays/$sessionId/waitingForNext'
      preLoaderRoute: typeof OverlaysSessionIdWaitingForNextImport
      parentRoute: typeof rootRoute
    }
    '/overlays/$sessionId/victory/$winner': {
      id: '/overlays/$sessionId/victory/$winner'
      path: '/overlays/$sessionId/victory/$winner'
      fullPath: '/overlays/$sessionId/victory/$winner'
      preLoaderRoute: typeof OverlaysSessionIdVictoryWinnerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/overlays/$sessionId/brb': typeof OverlaysSessionIdBrbRoute
  '/overlays/$sessionId/maps': typeof OverlaysSessionIdMapsRoute
  '/overlays/$sessionId/match': typeof OverlaysSessionIdMatchRoute
  '/overlays/$sessionId/startingSoon': typeof OverlaysSessionIdStartingSoonRoute
  '/overlays/$sessionId/thanks': typeof OverlaysSessionIdThanksRoute
  '/overlays/$sessionId/waitingForNext': typeof OverlaysSessionIdWaitingForNextRoute
  '/overlays/$sessionId/victory/$winner': typeof OverlaysSessionIdVictoryWinnerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/overlays/$sessionId/brb': typeof OverlaysSessionIdBrbRoute
  '/overlays/$sessionId/maps': typeof OverlaysSessionIdMapsRoute
  '/overlays/$sessionId/match': typeof OverlaysSessionIdMatchRoute
  '/overlays/$sessionId/startingSoon': typeof OverlaysSessionIdStartingSoonRoute
  '/overlays/$sessionId/thanks': typeof OverlaysSessionIdThanksRoute
  '/overlays/$sessionId/waitingForNext': typeof OverlaysSessionIdWaitingForNextRoute
  '/overlays/$sessionId/victory/$winner': typeof OverlaysSessionIdVictoryWinnerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/overlays/$sessionId/brb': typeof OverlaysSessionIdBrbRoute
  '/overlays/$sessionId/maps': typeof OverlaysSessionIdMapsRoute
  '/overlays/$sessionId/match': typeof OverlaysSessionIdMatchRoute
  '/overlays/$sessionId/startingSoon': typeof OverlaysSessionIdStartingSoonRoute
  '/overlays/$sessionId/thanks': typeof OverlaysSessionIdThanksRoute
  '/overlays/$sessionId/waitingForNext': typeof OverlaysSessionIdWaitingForNextRoute
  '/overlays/$sessionId/victory/$winner': typeof OverlaysSessionIdVictoryWinnerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/session/$sessionId'
    | '/overlays/$sessionId/brb'
    | '/overlays/$sessionId/maps'
    | '/overlays/$sessionId/match'
    | '/overlays/$sessionId/startingSoon'
    | '/overlays/$sessionId/thanks'
    | '/overlays/$sessionId/waitingForNext'
    | '/overlays/$sessionId/victory/$winner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/session/$sessionId'
    | '/overlays/$sessionId/brb'
    | '/overlays/$sessionId/maps'
    | '/overlays/$sessionId/match'
    | '/overlays/$sessionId/startingSoon'
    | '/overlays/$sessionId/thanks'
    | '/overlays/$sessionId/waitingForNext'
    | '/overlays/$sessionId/victory/$winner'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/session/$sessionId'
    | '/overlays/$sessionId/brb'
    | '/overlays/$sessionId/maps'
    | '/overlays/$sessionId/match'
    | '/overlays/$sessionId/startingSoon'
    | '/overlays/$sessionId/thanks'
    | '/overlays/$sessionId/waitingForNext'
    | '/overlays/$sessionId/victory/$winner'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  OverlaysSessionIdBrbRoute: typeof OverlaysSessionIdBrbRoute
  OverlaysSessionIdMapsRoute: typeof OverlaysSessionIdMapsRoute
  OverlaysSessionIdMatchRoute: typeof OverlaysSessionIdMatchRoute
  OverlaysSessionIdStartingSoonRoute: typeof OverlaysSessionIdStartingSoonRoute
  OverlaysSessionIdThanksRoute: typeof OverlaysSessionIdThanksRoute
  OverlaysSessionIdWaitingForNextRoute: typeof OverlaysSessionIdWaitingForNextRoute
  OverlaysSessionIdVictoryWinnerRoute: typeof OverlaysSessionIdVictoryWinnerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  OverlaysSessionIdBrbRoute: OverlaysSessionIdBrbRoute,
  OverlaysSessionIdMapsRoute: OverlaysSessionIdMapsRoute,
  OverlaysSessionIdMatchRoute: OverlaysSessionIdMatchRoute,
  OverlaysSessionIdStartingSoonRoute: OverlaysSessionIdStartingSoonRoute,
  OverlaysSessionIdThanksRoute: OverlaysSessionIdThanksRoute,
  OverlaysSessionIdWaitingForNextRoute: OverlaysSessionIdWaitingForNextRoute,
  OverlaysSessionIdVictoryWinnerRoute: OverlaysSessionIdVictoryWinnerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/new",
        "/session/$sessionId",
        "/overlays/$sessionId/brb",
        "/overlays/$sessionId/maps",
        "/overlays/$sessionId/match",
        "/overlays/$sessionId/startingSoon",
        "/overlays/$sessionId/thanks",
        "/overlays/$sessionId/waitingForNext",
        "/overlays/$sessionId/victory/$winner"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/new": {
      "filePath": "new.tsx"
    },
    "/session/$sessionId": {
      "filePath": "session.$sessionId.tsx"
    },
    "/overlays/$sessionId/brb": {
      "filePath": "overlays/$sessionId/brb.tsx"
    },
    "/overlays/$sessionId/maps": {
      "filePath": "overlays/$sessionId/maps.tsx"
    },
    "/overlays/$sessionId/match": {
      "filePath": "overlays/$sessionId/match.tsx"
    },
    "/overlays/$sessionId/startingSoon": {
      "filePath": "overlays/$sessionId/startingSoon.tsx"
    },
    "/overlays/$sessionId/thanks": {
      "filePath": "overlays/$sessionId/thanks.tsx"
    },
    "/overlays/$sessionId/waitingForNext": {
      "filePath": "overlays/$sessionId/waitingForNext.tsx"
    },
    "/overlays/$sessionId/victory/$winner": {
      "filePath": "overlays/$sessionId/victory.$winner.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
